from typing import Protocol

from app.schemas.state import BirdSchema


class BirdRepository(Protocol):
    def get_all(self) -> dict[str, BirdSchema]: ...
    def replace_all(self, birds: dict[str, BirdSchema]) -> None: ...


class CoupleRepository(Protocol):
    def get_all(self) -> dict[str, dict]: ...
    def replace_all(self, couples: dict[str, dict]) -> None: ...


class ContactRepository(Protocol):
    def get_all(self) -> dict[str, dict]: ...
    def replace_all(self, contacts: dict[str, dict]) -> None: ...


class OptionRepository(Protocol):
    def get_all(self) -> dict[str, list[str]]: ...
    def replace_all(self, options: dict[str, list[str]]) -> None: ...
